- package-lock.json
regenerate package lock from scratch
> Align package lock

- package-lock.json
- packages/flower-core/src/RulesMatcher.ts
- packages/flower-core/src/interfaces/Store.ts
- packages/flower-demo/package.json
- packages/flower-demo/src/index.tsx
Devtool used in demo flower
Removed duplicated type export from Core
> feat: add devtool to demo - remove duplicated export type

- package-lock.json
- packages/flower-react/README.md
regenerate package lock
add devtool snippet in flower-react readme.md
> chore: regenerate package lock and add devtool snippet to readme

- .github/PULL_REQUEST_TEMPLATE.md
- CODEOWNERS
- CONTRIBUTING.md
This PR adds a pull request template and info on how to contribute.
> docs: add contributing info and PR template

- packages/flower-react/README.md
The ReadME file has been updated with the correct commands for generating the source map.
> chore: update readme sourcemap commands

- .github/workflows/release.yaml
Updated a step into the release workflow
1) The push step has been updated from `git push` to `git push --set-upstream origin main`
There are no testable changes.
> ci: fix push command

- .github/workflows/release.yaml
Updated a step into the release workflow
The push step has been removed
There are no testable changes.
> ci: Update release.yaml

- .github/workflows/checks.yaml
- .github/workflows/release.yaml
This PR improves the release workflow by waiting for checks before updating the version and publishing to npm. It also re-enables pushing to main, because now main is protected by a ruleset with bypass for [Flower Bot](https://github.com/flower-github-bot).
- Wait for checks in release workflow
- `git push` to main
> Release pipeline improvement

- nx.json
- package-lock.json
- package.json
- packages/flower-demo/package.json
- packages/flower-devtool/.eslintrc.json
- packages/flower-devtool/CHANGELOG.md
- packages/flower-devtool/README.md
- packages/flower-devtool/bin/cli.js
- packages/flower-devtool/bin/cliUtils.js
- packages/flower-devtool/bin/utilsAST.js
- packages/flower-devtool/jest.config.ts
- packages/flower-devtool/package.json
- packages/flower-devtool/project.json
- packages/flower-devtool/src/index.ts
- packages/flower-devtool/src/screenshot.native.js
- packages/flower-devtool/src/screenshot.ts
- packages/flower-devtool/src/tools.ts
- packages/flower-devtool/tsconfig.json
- packages/flower-devtool/tsconfig.lib.json
- packages/flower-devtool/tsconfig.spec.json
This PR adds the Flower DevTool code to the monorepo.
- Flower DevTool code and release
> Feat: add devtool

- packages/flower-devtool/src/tools.ts
> fix: clean code

- package-lock.json
- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/index.ts
- packages/flower-devtool/src/tools.ts
- packages/flower-react/src/components/Flower.tsx
- packages/flower-react/src/components/useFlower.ts
- packages/flower-react/src/index.ts
> fix: remove global.window object

- package-lock.json
- packages/flower-core/tsconfig.lib.json
- packages/flower-react/tsconfig.lib.json
restore documentation comments into d.ts
> fix: restore documentation comments into d.ts

- package-lock.json
- packages/flower-react/src/components/types/FlowerHooks.ts
- packages/flower-react/src/components/useFlower.ts
expose start node id from hook useFlower
> feat: expose start node id from hook useFlower

- package-lock.json
- packages/flower-devtool/bin/cli.js
- packages/flower-devtool/package.json
- packages/flower-devtool/src/tools.ts
> File preview sourcemap

- packages/flower-devtool/package.json
> chore: change peerDependency flower-core version in flower-devtool

- .github/PULL_REQUEST_TEMPLATE.md
- packages/flower-devtool/package.json
- packages/flower-devtool/rollup.config.js
> fix: cli bin

- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateSelectors.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/__tests__/flowerCoreSelector.test.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-core/src/interfaces/SelectorsInterface.ts
- packages/flower-core/src/interfaces/Store.ts
- packages/flower-demo/src/Examples/Example9.tsx
- packages/flower-react/src/__tests__/FlowerField.test.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerHooks.ts
- packages/flower-react/src/components/useFlowerForm.ts
- packages/flower-react/src/selectors.ts
Added reset form and custom errors
> Untouched form

- package-lock.json
- packages/flower-demo/src/index.tsx
- packages/flower-devtool/bin/cli.js
- packages/flower-devtool/src/tools.ts
- packages/flower-react/README.md
Added public key and secret key to use devtool remote
> Devtool sessionid

- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateSelectors.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/__tests__/flowerCoreStateFunctions.test.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-core/src/interfaces/SelectorsInterface.ts
- packages/flower-core/src/interfaces/Store.ts
- packages/flower-core/src/interfaces/UtilsInterface.ts
- packages/flower-demo/src/Examples/.flower/Example9.metadata.json
- packages/flower-demo/src/Examples/Example9.tsx
- packages/flower-demo/src/Examples/styles.css
- packages/flower-demo/src/index.tsx
- packages/flower-react/src/__tests__/FlowerField.test.tsx
- packages/flower-react/src/components/Flower.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerField.ts
- packages/flower-react/src/components/useFlowerForm.ts
- packages/flower-react/src/selectors.ts
Fixed a bug in the context of the current node when used with a retain.
Fixed the default value in FlowerField.
> Feat: form enhanced with custom errors 

- packages/flower-devtool/src/tools.ts
> Fix: devtool sessionid

- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateSelectors.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/__tests__/coreUtils.test.ts
- packages/flower-core/src/__tests__/flowerCoreSelector.test.ts
- packages/flower-core/src/__tests__/flowerCoreStateFunctions.test.ts
- packages/flower-core/src/__tests__/flowerCoreStateUtils.test.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-core/src/interfaces/SelectorsInterface.ts
- packages/flower-core/src/interfaces/Store.ts
- packages/flower-core/src/interfaces/UtilsInterface.ts
- packages/flower-demo/src/Examples/Example9.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerField.ts
- packages/flower-react/src/components/types/FlowerHooks.ts
- packages/flower-react/src/components/useFlowerForm.ts
- packages/flower-react/src/selectors.ts
add status submited in form node
> feat: add status submited in form node

- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateSelectors.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/__tests__/coreUtils.test.ts
- packages/flower-core/src/__tests__/flowerCoreSelector.test.ts
- packages/flower-core/src/__tests__/flowerCoreStateFunctions.test.ts
- packages/flower-core/src/__tests__/flowerCoreStateUtils.test.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-core/src/interfaces/SelectorsInterface.ts
- packages/flower-core/src/interfaces/Store.ts
- packages/flower-core/src/interfaces/UtilsInterface.ts
- packages/flower-demo/src/Examples/Example9.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerField.ts
- packages/flower-react/src/components/types/FlowerHooks.ts
- packages/flower-react/src/components/useFlowerForm.ts
- packages/flower-react/src/selectors.ts
> Feat set field data

- packages/flower-core/src/FlowerCoreStateFunctions.ts
reset form dirty and submitted
> fix: reset form dirty and submitted

- packages/flower-core/src/FlowerCoreStateFunctions.ts
> fix: reset form dirty

- package-lock.json
- packages/flower-devtool/bin/cli.js
- packages/flower-devtool/src/tools.ts
> fix(web): add route name devtool

- package-lock.json
- packages/flower-react/src/__tests__/form.test.tsx
- packages/flower-react/src/components/types/FlowerHooks.ts
- packages/flower-react/src/components/useFlowerForm.ts
added new utils to retrieve form status
> feat: added new utils to retrieve form status

- package-lock.json
- packages/flower-core/src/interfaces/CoreInterface.ts
- packages/flower-core/src/interfaces/Store.ts
- packages/flower-core/src/rules-matcher/interface.ts
- packages/flower-react/src/components/types/FlowerField.ts
- packages/flower-react/src/components/types/FlowerRule.ts
- packages/flower-react/src/components/types/FlowerValue.ts
Fixed some wrong example in flower react docs for rules
> fix: rulesOperators example fixed

- package-lock.json
- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/devtoolState.ts
- packages/flower-core/src/index.ts
- packages/flower-core/src/interfaces/CoreInterface.ts
- packages/flower-core/src/rules-matcher/interface.ts
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerRule.ts
> fix: resolves RulesObject type and circular dependency

- package-lock.json
- packages/flower-react/src/components/types/FlowerNavigate.ts
- packages/flower-react/src/index.ts
Types of navigation actions are exposed to make it easier to create custom components wrapped with `<FlowerNavigate />`
> feat: expose FlowerNavigateActions type

- package-lock.json
- packages/flower-react/src/components/FlowerField.tsx
fix: remove wrong deps in FlowerField onChange
> fix: remove wrong deps in FlowerField onChange

- packages/flower-react/src/components/types/FlowerHooks.ts
> chore: fix type getCurrentNodeId

- package-lock.json
- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateSelectors.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-core/src/interfaces/SelectorsInterface.ts
- packages/flower-core/src/interfaces/Store.ts
- packages/flower-demo/src/Examples/Example9.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerField.ts
- packages/flower-react/src/components/types/FlowerHooks.ts
- packages/flower-react/src/components/useFlowerForm.ts
- packages/flower-react/src/selectors.ts
added focus login in FlowerField
> feat: added "hasFocus" in useFlower and "focused" on FlowerField

- package-lock.json
- packages/flower-react/src/__tests__/FlowerField.test.tsx
- packages/flower-react/src/components/FlowerField.tsx
> fix: avoid validate hidden field

- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-demo/src/App.tsx
- packages/flower-demo/src/Examples/Example11.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerField.ts
added remove value on hide element
> feat: added remove value on hide element

- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-react/src/components/FlowerField.tsx
derivated dirty from form values
> chore: derivated dirty from form values

- .markdownlint-cli2.jsonc
- .vscode/extensions.json
- .vscode/settings.json
- package-lock.json
- package.json
- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-demo/src/App.tsx
- packages/flower-demo/src/Examples/Example11.tsx
- packages/flower-react/README.md
- packages/flower-react/src/__tests__/FlowerField.test.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerField.ts
> Align release to main

- .markdownlint-cli2.jsonc
- .vscode/extensions.json
- .vscode/settings.json
- package-lock.json
- package.json
- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-core/src/FlowerCoreStateUtils.ts
- packages/flower-core/src/interfaces/ReducerInterface.ts
- packages/flower-demo/src/App.tsx
- packages/flower-demo/src/Examples/Example11.tsx
- packages/flower-react/README.md
- packages/flower-react/src/__tests__/FlowerField.test.tsx
- packages/flower-react/src/components/FlowerField.tsx
- packages/flower-react/src/components/types/FlowerField.ts
> feat: destroyOnHide

- package-lock.json
- packages/flower-core/src/FlowerCoreStateFunctions.ts
- packages/flower-react/CHANGELOG.md
> feat: Remove data blank from init nodes

- package-lock.json
- packages/flower-core/src/FlowerCoreStateFunctions.ts
> fix: check if initialData is empty
